/* The dispatch clock's logic, kept free of any runtime so the Worker
   (worker.mjs) and the tests (.build/test-dispatch-clock.mjs) share it.

   schedule.json (generated by .build/tune-schedules.mjs) lists slots as
   { workflow, day: "Mon".."Sun" | "daily", time: "HH:MM", label } in
   Australia/Sydney wall-clock time. A slot is due in the minute whose
   Sydney day and clock match it. Converting here, per tick, is what makes
   the table DST-proof: nothing in it is UTC. `fetch` is the only runtime
   dependency (global in Workers and in Node 18+); the tests stub it. */

export const TZ = "Australia/Sydney";

// en-US gives fixed three-letter weekdays; h23 keeps midnight "00", not "24"
const fmt = new Intl.DateTimeFormat("en-US", {
  timeZone: TZ, weekday: "short", hour: "2-digit", minute: "2-digit", hourCycle: "h23",
});

export function sydneyClock(date) {
  const p = Object.fromEntries(fmt.formatToParts(date).map((x) => [x.type, x.value]));
  return { day: p.weekday, time: `${p.hour}:${p.minute}` };
}

// A dispatch names a workflow file in a URL path — take nothing else.
export const SAFE_WORKFLOW = /^[a-z0-9][a-z0-9-]*\.yml$/;

export function dueWorkflows(table, date) {
  const { day, time } = sydneyClock(date);
  const due = new Set();
  for (const s of table.slots || [])
    if ((s.day === "daily" || s.day === day) && s.time === time && SAFE_WORKFLOW.test(s.workflow)) due.add(s.workflow);
  return [...due].sort();
}

// The next `n` minutes that dispatch anything, from `from` (for the status page).
export function nextSlots(table, from, n = 10, horizonMinutes = 8 * 1440) {
  const out = [];
  const t = new Date(Math.ceil(from.getTime() / 60000) * 60000);
  for (let i = 0; i < horizonMinutes && out.length < n; i++, t.setTime(t.getTime() + 60000)) {
    const due = dueWorkflows(table, t);
    if (due.length) out.push({ at: t.toISOString(), sydney: sydneyClock(t), workflows: due });
  }
  return out;
}

// ---- the tick: read the table, dispatch what is due ------------------------------
const UA = "auspol-dispatch-clock (+https://github.com/joshborgnolo/auspol-tracker)";

export async function loadTable(env) {
  const res = await fetch(env.TABLE_URL, { headers: { "user-agent": UA }, cf: { cacheTtl: 300 } });
  if (!res.ok) throw new Error(`schedule.json fetch answered HTTP ${res.status}`);
  return res.json();
}

export async function tick(when, env) {
  const table = await loadTable(env);
  const due = dueWorkflows(table, when);
  const results = [];
  for (const wf of due) {
    const res = await fetch(`https://api.github.com/repos/${env.REPO}/actions/workflows/${wf}/dispatches`, {
      method: "POST",
      headers: {
        authorization: `Bearer ${env.GITHUB_TOKEN}`,
        accept: "application/vnd.github+json",
        "x-github-api-version": "2022-11-28",
        "content-type": "application/json",
        "user-agent": UA,
      },
      body: JSON.stringify({ ref: "main" }),
    });
    // 204 = started; anything else lands in the Worker's logs
    results.push({ workflow: wf, status: res.status });
    if (res.status !== 204) console.error(`dispatch ${wf}: HTTP ${res.status} ${await res.text()}`);
  }
  if (results.length) console.log(JSON.stringify({ at: when.toISOString(), sydney: sydneyClock(when), results }));
  return results;
}
